default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root

development:
  <<: *default
  database: advent2016_development

test: &test
  <<: *default
  database: advent2016_test

production:
  <<: *default
  database: advent2016_production
